### ISSUE TITLE
Discord server link is broken

### ISSUE THREAD

**Issue by vassalo** [7h30th3r0n3/Evil-M5Core2#13]
Hey, I noticed that the discord server link available in the README is not working. Can you send me a new invite? Or update the README one.
Thx!

**Comment by 7h30th3r0n3** [comment]
> Hey, I noticed that the discord server link available in the README is not working. Can you send me a new invite? Or update the README one. Thx!

Here it is : https://discord.com/invite/r68guFb6

Thx for the report, I'm also updating the readme
