### ISSUE TITLE
Evil-Cardputer, (No navigation)

### ISSUE THREAD

**Issue by Hoyasis** [7h30th3r0n3/Evil-M5Core2#14]
So I've been having this issue where I put everything from the SD card file into my SD card flash the firmware and everything looks great until I try to navigate, no function buttons work other than the GO button on the top of the device, so long story short i can only select what is already selected. I believe that I did everything right but every single thing I do wont fix my issue.

Also the discord link is invalid.

**Comment by 7h30th3r0n3** [comment]
Thx for using the project, 

Well, for now it's a "dirty" portage from Evil-AtomS3, so you got only one button to navigate which is the go button, one fast press to change and one long press to select things but it's planned to use the keyboard in futur to ensure better navigating experience, 

Discord link fixed 🤙
