### ISSUE TITLE
Compiler error 

### ISSUE THREAD

**Issue by loewal** [7h30th3r0n3/Evil-M5Core2#15]
Getting this today:
In file included from /Users/loewal/Documents/Arduino/libraries/M5GFX/src/lgfx/v1/platforms/esp32/../esp32/common.hpp:20,
                 from /Users/loewal/Documents/Arduino/libraries/M5GFX/src/lgfx/v1/platforms/esp32/../common.hpp:22,
                 from /Users/loewal/Documents/Arduino/libraries/M5GFX/src/lgfx/v1/platforms/esp32/Bus_SPI.hpp:57,
                 from /Users/loewal/Documents/Arduino/libraries/M5GFX/src/lgfx/v1/platforms/device.hpp:42,
                 from /Users/loewal/Documents/Arduino/libraries/M5GFX/src/M5GFX.h:19,
                 from /Users/loewal/Documents/Arduino/libraries/M5Unified/src/M5Unified.hpp:19,
                 from /Users/loewal/Documents/Arduino/libraries/M5Unified/src/M5Unified.h:5,
                 from /Users/loewal/Documents/Arduino/Evil-M5Core3-1-1-9/Evil-M5Core3-1-1-9.ino:37:
/Users/loewal/Documents/Arduino/libraries/M5GFX/src/lgfx/v1/platforms/esp32/../esp32/../../misc/DataWrapper.hpp:27:10: fatal error: ../../utility/pgmspace.h: No such file or directory
 #include "../../utility/pgmspace.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

Can you help?

**Comment by 7h30th3r0n3** [comment]
Hey ! This error seem to be from M5GFX library, maybe you should try to reinstall M5Stack librairie which contain M5GFX

**Comment by loewal** [comment]
Solved it, thanks!

**Comment by 7h30th3r0n3** [comment]
closing because resolved
