### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by LuckyFishGeek** [7h30th3r0n3/Evil-M5Core2#19]
c:/users/administrator/appdata/local/arduino15/packages/m5stack/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\Administrator\AppData\Local\Arduino15\packages\m5stack\hardware\esp32\2.1.1/tools/sdk/esp32/lib\libnet80211.a(ieee80211_output.o): in function `ieee80211_raw_frame_sanity_check':
(.text.ieee80211_raw_frame_sanity_check+0x5c): multiple definition of `ieee80211_raw_frame_sanity_check'; sketch\Evil-M5Core2-1-2-1.ino.cpp.o:C:\Users\Administrator\Desktop\Evil-M5Core2-main\Evil-M5Core2-1-2-1/Evil-M5Core2-1-2-1.ino:5044: first defined here
collect2.exe: error: ld returned 1 exit status

**Comment by 7h30th3r0n3** [comment]
Did you use the patch script of esp32 in deauth_prerequis as described
