### ISSUE TITLE
Client Sniffing and Deauth - Problem with viewing

### ISSUE THREAD

**Issue by ianfs2** [7h30th3r0n3/Evil-M5Core2#22]
![IMG_20240516_140718](https://github.com/7h30th3r0n3/Evil-M5Core2/assets/47403239/4e4c9df2-9d9b-44ac-995b-7e06c67c15a4)

When there are many Wi-Fi networks, the messages get stuck on top and become difficult to read.

**Comment by 7h30th3r0n3** [comment]
Hey ! Thx for using the project ! 

Yeah I planned to make a background box with different colour on the back to be able to read it better, it's already added on Todo 👍

**Comment by ianfs2** [comment]
It's very cool! I'm still testing it, but I think it's really cool.


I'm using a translator, maybe some messages are wrong.

**Comment by 7h30th3r0n3** [comment]
Glad that you like it 😊 and it's just a begining haha 😜
You are understandable 👍
