### ISSUE TITLE
[idea]  separate 'settings' submenu

### ISSUE THREAD

**Issue by Unixware** [7h30th3r0n3/Evil-M5Core2#23]
I think a separate settings submenu would be nice with options like brightness (already exist) and font size (please!)- this is more suitable for cardputer, the screen is so friggin small, thanks!

**Comment by 7h30th3r0n3** [comment]
Hey ! Thx for using the project and for your recommendations, good news it's planned ! Already asked on the discord, and added to roadmap,

Refactorisation of the Cardputer should be pushed soon with a x1.5 magnification to ensure proper view of all the things, 

And refactorisation of the menu is planned when more no WiFi functionalities are pushed, stay tuned and feel free to come on the discord at the end of the readme to get more update ☺️
