### ISSUE TITLE
M5Core not working on internal battery

### ISSUE THREAD

**Issue by nash68** [7h30th3r0n3/Evil-M5Core2#28]
When I remove the usb power supply, the M5Core is switched off and generates some strange sounds (tik... tik... tik...).
Any option to keep the product running on its own internal (little) battery ?
Yours.

**Comment by 7h30th3r0n3** [comment]
Can you ensure that you disable PSRAM before compiling ? If enable it can cause bootloop

**Comment by nash68** [comment]
Did not try, For the moment I use it only with external battery anyway :-)
