### ISSUE TITLE
Buttons don’t do anything

### ISSUE THREAD

**Issue by Rockedstar44** [7h30th3r0n3/Evil-M5Core2#46]
Firmware looks installed- goes through the boot sequence. Once on the main menu none of the buttons do anything.

**Comment by 7h30th3r0n3** [comment]
Hi ! Thx for using the project, 

To better understand the issue, could you please provide a bit more information?

- The exact model of the board you are using.
- The .ino file you flashed (or a link to it).
- Which version.
- The method you used to flash the firmware (e.g., through Arduino IDE, esptool, M5burner etc.).

This information will help us diagnose the problem and provide you with a solution more efficiently.
