### ISSUE TITLE
Selections Appear to be dysfunctional.

### ISSUE THREAD

**Issue by xcs011** [7h30th3r0n3/Evil-M5Core2#48]
The "Deauther" selection begins a karma attack instead, and functions exactly the same as the listed karma option. 

It even reports karma failed... when you exit it

**Comment by xcs011** [comment]
To clarify this happens on the cardputer, I havent tested it elsewhere

**Comment by xcs011** [comment]
Only occurs on m5launcher version, m5burner most recent version works fine.

**Comment by 7h30th3r0n3** [comment]
Can you explain what happened ?
