### ISSUE TITLE
Ultra noob here

### ISSUE THREAD

**Issue by sukoshi1507** [7h30th3r0n3/Evil-M5Core2#7]
Switching from 1.1.4 to 1.1.5 my M5 fire is bricked with this new version.

When i switch back to 1.1.4, all is working comme il faut :p

Only changes are the mandatory checks + adding the new tinyGPS++ library.

any clue ?

**Comment by 7h30th3r0n3** [comment]
Hey ! Thx for using the project ! 

It's should be related to GPS PIN, because they are different from Core2 and fire you need to comment and uncomment part of the code, 

Check line stamped with a big change this 😜

**Comment by 7h30th3r0n3** [comment]
V1.1.6 is here and fix the problem, closing the issue
