### ISSUE TITLE
having an issue. its giving me an error

### ISSUE THREAD

**Issue by MannyV143** [7h30th3r0n3/Evil-M5Core2#8]
https://github.com/7h30th3r0n3/Evil-M5Core2/blame/f9159044ce2548aac4f7169e7cf65c46a44e804c/Evil-M5Core2-1-1-6.ino#L1509

**Comment by 7h30th3r0n3** [comment]
Hi ! Thx for using the project !

Can you share to me the model of M5 you are using, the error generated and the exact issue ( won't compile, stuck, loop reboot).

**Comment by kf5gxz** [comment]
I'm getting an error as well, screenshot attached. M5FIRE.
[M5FIRE error EVILM5.docx](https://github.com/7h30th3r0n3/Evil-M5Core2/files/14204147/M5FIRE.error.EVILM5.docx)

**Comment by 7h30th3r0n3** [comment]
> I'm getting an error as well, screenshot attached. M5FIRE. [M5FIRE error EVILM5.docx](https://github.com/7h30th3r0n3/Evil-M5Core2/files/14204147/M5FIRE.error.EVILM5.docx)

For this error you just need to add TinyGpsPlus librairie that you can find on manage librairies,

**Comment by 7h30th3r0n3** [comment]
closing due to no anwser about the problem
