### ISSUE TITLE
 support for m5go core original?

### ISSUE THREAD

**Issue by donniebrasc** [7h30th3r0n3/Evil-M5Core2#9]
i  cant seem to get the m5core to work with this project. is there a fork for them?

**Comment by 7h30th3r0n3** [comment]
Hi ! 
The Evil-M5Core2 project should work on m5go, 
Can you provide more details about what happen on your side ? 
( error, symptoms, crash ?)

**Comment by donniebrasc** [comment]
I was experiencing black screens after flashing but ive resolved the problem. I found a fork that was compiled specifically. Thanks for responding
Sent from Yahoo Mail on Android 
 
  On Wed, Feb 21, 2024 at 8:57 AM, ***@***.***> wrote:   


Hi !
The Evil-M5Core2 project should work on m5go,
Can you provide more details about what happen on your side ?
( error, symptoms, crash ?)
